export type RailOperator = {
  name: string;
  country: string;
  code?: string;
};

// Curated European rail operators: national carriers, notable open-access and
// sleeper brands, and the larger regional franchises, sorted by name.
export const RAIL_OPERATORS: RailOperator[] = [
  { name: "Arlanda Express", country: "SE" },
  { name: "Arriva Nederland", country: "NL" },
  { name: "Arriva vlaky", country: "CZ" },
  { name: "Astra Trans Carpatic", country: "RO" },
  { name: "Avanti West Coast", country: "GB" },
  { name: "BDŽ", country: "BG" },
  { name: "BLS", country: "CH" },
  { name: "Belarusian Railway", country: "BY" },
  { name: "c2c", country: "GB" },
  { name: "CFL", country: "LU" },
  { name: "CFM", country: "MD" },
  { name: "CFR Călători", country: "RO" },
  { name: "CP Comboios de Portugal", country: "PT" },
  { name: "Caledonian Sleeper", country: "GB" },
  { name: "Chiltern Railways", country: "GB" },
  { name: "CrossCountry", country: "GB" },
  { name: "ČD České dráhy", country: "CZ" },
  { name: "DSB", country: "DK" },
  { name: "Deutsche Bahn", country: "DE" },
  { name: "East Midlands Railway", country: "GB" },
  { name: "Elron", country: "EE" },
  { name: "Eurostar", country: "FR" },
  { name: "European Sleeper", country: "NL" },
  { name: "Euskotren", country: "ES" },
  { name: "FGC", country: "ES" },
  { name: "Fertagus", country: "PT" },
  { name: "FlixTrain", country: "DE" },
  { name: "Flytoget", country: "NO" },
  { name: "GYSEV", country: "HU" },
  { name: "Go-Ahead Nordic", country: "NO" },
  { name: "Grand Central", country: "GB" },
  { name: "Great Western Railway", country: "GB" },
  { name: "Greater Anglia", country: "GB" },
  { name: "HŽPP", country: "HR" },
  { name: "Heathrow Express", country: "GB" },
  { name: "Hellenic Train", country: "GR" },
  { name: "Hull Trains", country: "GB" },
  { name: "Iarnród Éireann", country: "IE" },
  { name: "Iryo", country: "ES" },
  { name: "Italo NTV", country: "IT" },
  { name: "Koleje Mazowieckie", country: "PL" },
  { name: "LNER", country: "GB" },
  { name: "LTG Link", country: "LT" },
  { name: "Leo Express", country: "CZ" },
  { name: "Lumo", country: "GB" },
  { name: "MÁV-START", country: "HU" },
  { name: "Merseyrail", country: "GB" },
  { name: "Metronom", country: "DE" },
  { name: "NS", country: "NL" },
  { name: "National Express Germany", country: "DE" },
  { name: "Northern", country: "GB" },
  { name: "ODEG", country: "DE" },
  { name: "Ouigo", country: "FR" },
  { name: "Ouigo España", country: "ES" },
  { name: "PKP Intercity", country: "PL" },
  { name: "Pasažieru vilciens", country: "LV" },
  { name: "PolRegio", country: "PL" },
  { name: "Renfe", country: "ES" },
  { name: "RegioJet", country: "CZ" },
  { name: "Regio Călători", country: "RO" },
  { name: "Rhätische Bahn", country: "CH" },
  { name: "SBB CFF FFS", country: "CH" },
  { name: "SJ", country: "SE" },
  { name: "SJ Norge", country: "NO" },
  { name: "SKM Trójmiasto", country: "PL" },
  { name: "SNCB/NMBS", country: "BE" },
  { name: "SNCF", country: "FR" },
  { name: "ScotRail", country: "GB" },
  { name: "Slovenske železnice", country: "SI" },
  { name: "Snälltåget", country: "SE" },
  { name: "Southeastern", country: "GB" },
  { name: "Southern", country: "GB" },
  { name: "Srbija Voz", country: "RS" },
  { name: "TCDD Taşımacılık", country: "TR" },
  { name: "TGV Lyria", country: "CH" },
  { name: "Thameslink", country: "GB" },
  { name: "Transilien", country: "FR" },
  { name: "TransPennine Express", country: "GB" },
  { name: "Transdev", country: "DE" },
  { name: "Transport for Wales", country: "GB" },
  { name: "Trenitalia", country: "IT" },
  { name: "Trenord", country: "IT" },
  { name: "Translink NI Railways", country: "GB" },
  { name: "Ukrzaliznytsia", country: "UA" },
  { name: "VR", country: "FI" },
  { name: "Vy", country: "NO" },
  { name: "WESTbahn", country: "AT" },
  { name: "West Midlands Railway", country: "GB" },
  { name: "ZSSK", country: "SK" },
  { name: "Zentralbahn", country: "CH" },
  { name: "ÖBB", country: "AT" },
  { name: "ÖBB Nightjet", country: "AT" },
  { name: "Öresundståg", country: "SE" },
];

export function searchRailOperators(query: string, limit = RAIL_OPERATORS.length): RailOperator[] {
  const normalizedQuery = query.trim().toLocaleLowerCase();
  if (!normalizedQuery) return RAIL_OPERATORS.slice(0, limit);

  return RAIL_OPERATORS.filter((operator) =>
    operator.name.toLocaleLowerCase().includes(normalizedQuery) ||
    operator.country.toLocaleLowerCase() === normalizedQuery,
  ).slice(0, limit);
}
